{% set version = "1.1.3" %}

package:
  name: doxybook2
  version: {{ version }}

source:
  url: https://github.com/matusnovak/doxybook2/releases/download/v{{ version }}/doxybook2-linux-arm64-v{{ version }}.zip # [linux]
  url: https://github.com/matusnovak/doxybook2/releases/download/v{{ version }}/doxybook2-osx-amd64-v{{ version }}.zip # [osx]
  url: https://github.com/matusnovak/doxybook2/releases/download/v{{ version }}/doxybook2-windows-win64-v{{ version }}.zip # [win]
  sha256: 093aa5f06f3f38747cbb16831f2856912e2b748fece03c85a53e2717b435cac7 # [linux]
  sha256: 71d551f3fd62c507b295c2d8401bef3bab8563c302076c94f0f65fed5dd9d883 # [osx]
  sha256: f34fe770384c37a1b018e8519d8ddd9a816bd5b053e0664b623bc2be8b7ffbbb # [win]

build:
  number: 0
  script: cp -r $SRC_DIR/* $PREFIX/ # [not win]
  script: python -c "from distutils.dir_util import copy_tree; copy_tree(\"%SRC_DIR%\", \"%PREFIX%\")" # [win]

about:
  home: https://github.com/matusnovak/doxybook2/
  license: MIT
  summary: ' Doxygen XML to Markdown (or JSON) '
  description: |
    Doxygen XML to Markdown (or JSON) converter. Generate beautiful
    C++ documentation by converting Doxygen XML output into markdown
    pages via MkDocs, Hugo, VuePress, GitBook, Docsify, or your custom
    generator. Also comes with an optional templating mechanism and
    extensive configuration file.
